version: '2'

services:

    web:
        command: npm run watch
        build: .
        volumes:
          - .:/app/src
          - /app/src/node_modules

    app:
        command: python run.py
        build: .
        ports:
          - "5000:5000"
        volumes:
          - .:/app/src
        links:
          - web
